2017-03-27 09:24:16: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 09:24:16: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 09:24:16: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 09:24:16: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 09:24:30: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 09:24:30: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 09:24:30: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 09:24:30: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 09:24:31: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 09:44:57: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 09:51:29: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 10:00:16: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 10:03:01: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.wQh1k8mXtn4yGgQ8LDh(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.SendByteCallBack(IAsyncResult ar)
2017-03-27 11:18:42: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 11:18:42: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 11:18:42: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 11:18:42: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 11:18:42: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 11:18:42: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 11:18:42: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 11:18:42: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 11:18:42: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 11:19:28: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 11:55:03: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 11:55:03: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 11:55:03: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 14:12:40: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 14:12:40: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 14:12:40: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 14:12:53: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 14:12:53: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 14:12:53: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 14:12:54: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 15:39:55: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 15:39:55: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 15:39:55: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-03-27 15:39:55: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
