2017-05-19 09:08:51: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-05-19 09:44:03: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-05-19 09:47:48: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-05-19 09:59:10: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-05-19 09:59:19: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-05-19 09:59:28: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-05-19 09:59:52: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-05-19 10:31:02: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-05-19 10:31:02: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2017-05-19 10:31:02: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
