2016-07-15 08:29:53: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-07-15 09:16:36: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-07-15 09:16:50: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-07-15 09:46:54: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-07-15 09:49:43: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-07-15 10:12:50: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-07-15 10:12:50: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-07-15 10:12:50: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-07-15 14:49:13: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-07-15 15:44:35: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-07-15 15:53:03: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
