2016-09-02 08:58:52: 无法访问已释放的对象。
对象名:“System.Net.Sockets.Socket”。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult, SocketError& errorCode)
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-09-02 11:20:21: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-09-02 11:20:21: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.wQh1k8mXtn4yGgQ8LDh(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.SendByteCallBack(IAsyncResult ar)
2016-09-02 11:20:21: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.wQh1k8mXtn4yGgQ8LDh(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.SendByteCallBack(IAsyncResult ar)
2016-09-02 14:17:30: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
2016-09-02 14:46:55: 你的主机中的软件中止了一个已建立的连接。   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 Yinrg.Net.Sockets.SocketClient.s91nev5CPITrFiQpWCt(Object , Object )
   在 Yinrg.Net.Sockets.SocketClient.GsnOTWuuJ(IAsyncResult  )
